version: "3.8"

services:
  ai-memory-orchestrator-worker:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8100
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "8100:8100"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks: [appnet]

networks:
  appnet:
